workflows:
  build_apk:
    name: Build Flutter APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Clean & upgrade dependencies
        script: |
          flutter clean
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Generate launcher icons
        script: |
          flutter pub run flutter_launcher_icons:main

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - shallagehsaeed@gmail.com
