name: Alert_X
description: "مدیریت سیگنال چارت"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.0
  firebase_messaging: ^14.6.0
  http: ^1.2.2
  photo_view: ^0.15.0
  shared_preferences: ^2.1.1
  permission_handler: ^11.3.1
  path_provider: ^2.0.15
  video_player: ^2.6.0
  flutter_secure_storage: ^4.2.0
  provider: ^6.0.1
  cached_network_image: ^3.2.0
  flutter_local_notifications: ^17.2.1
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/a.mp4
